### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by someguy9**
Added two new tools (url extractor & sentence case converter)

### CODE REVIEW

**Comment by someguy9** [comment]
Thanks @J0rgeSerran0 for an epic list!

**Comment by J0rgeSerran0** [comment]
I have added a Contributors append at the bottom... and you are the first one! :D

**Comment by someguy9** [comment]
Ooo thank you, I figured a lot of people made this! I just submitted a new commit with more tools as well

**Comment by J0rgeSerran0** [comment]
Well, there is another person that I am going to add too... but I created and added the whole content

**Pull request merged**
